// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liaitnduksenlasikoti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpYWl0bmR1a3Nlbmxhc2lrb3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjUzNjAsImV4cCI6MjA2NTAwMTM2MH0.B-2SE2TStGLDRo8wWsANQ9e8vlQiXqGlfeehRkygpag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);